export const postsData = [
  {
    id: 1,
    image:
      "https://imgproxy.onliner.by/ifzJjJW_T4y1Ytu_X1TMwrzOF3KqkBtzrHMMLBJSgzM/rt:fill/s:1534:740/aHR0cHM6Ly9jb250/ZW50Lm9ubGluZXIu/YnkvbmV3cy9sYXJn/ZS84YzZjODdhMWJj/NWZhNTY0NzYwYjQ0/NzQ3OWEyMGNlZi5q/cGc",
    text: "Если долго ехать по Октябрьской — одной из главных улиц в Пружанах, — можно наткнуться на прекрасное нечто. Это бык (или все же зубр?), лежащий на капоте кабриолета Alfa Romeo. Некоторые местные относятся к этому муралу со снисходительной усмешкой. Но, по-моему, он просто восхитителен. И, что самое интересное, в нем зарыто достаточное количество пасхалок, чтобы сразу понять, в какой город мы приехали.",
    date: "2021-12-12",
    lesson_num: 1,
    title:
      "Шеф-повар из Америки, герб как у Alfa Romeo и огромный опен-эйр. Как (не)скромный райцентр готовится к большому рок-фесту",
    favourites: false,
    popular: true,
    author: 4,
  },
  {
    id: 2,
    image: "https://placehold.co/400x400",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "В Сморгони сотрудники МЧС спасли из воды обессиленную собаку",
    favourites: true,
    popular: false,
    author: 5,
  },
  {
    id: 3,
    image: "https://placehold.co/400x400",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title:
      "«Подружка», «Мила», «Остров чистоты»: чем отличаются и что по ценам?",
    favourites: false,
    popular: true,
    author: 3,
  },
  {
    id: 4,
    image: "https://placehold.co/400x400",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "Был Geely, стал Renault. Monjaro будут продавать под другой маркой",
    favourites: true,
    popular: false,
    author: 4,
  },
  {
    id: 5,
    image: "https://placehold.co/400x400",
    text: "Любые нововведения вызывают массу вопросов. Для того чтобы ответить на них, «транспортники» и налоговая провели встречу с представителями служб такси. Выяснилось, что некоторые перевозчики и водители не знают даже базовых правил, поэтому на мероприятии обсуждались и давнишние нормы. Мы собрали в один текст самые острые и волнующие вопросы, прозвучавшие там.",
    date: "2021-12-12",
    lesson_num: 1,
    title:
      "Таксист не сможет использовать автомобиль в личных целях и хранить его у себя во дворе? До введения нового реестра осталось полгода, но вопросов еще много",
    favourites: true,
    popular: false,
    author: 5,
  },
  {
    id: 6,
    image: "https://placehold.co/100x100",
    text: "Лето — сезон, когда белорусы чаще обычного выезжают за пределы страны. Оставаться без связи в дороге (как в личной, так и тем более в деловой поездке) сегодня как минимум некомфортно. Скорее всего, обойтись лишь офлайн-сервисами ну удастся. Недавно мы побывали в Милане и, кроме отельного Wi-Fi, заполучили мобильную связь с интернетом, звонками, СМС-сообщениями за относительно доступные деньги. Рассказываем о тонкостях.",
    date: "2021-12-12",
    lesson_num: 1,
    title:
      "Личный опыт: как получить быстрый 5G-интернет в путешествии и не переплатить?",
    favourites: true,
    popular: true,
    author: 3,
  },
  {
    id: 7,
    image: "https://placehold.co/100x100",
    text: "NASA провело исследование образцов астероида Бенну, которые прибыли на Землю силами миссии OSIRIS-REx. Если коротко, астероид мог образоваться в недрах водного мира, сообщает Space.",
    date: "2021-12-12",
    lesson_num: 1,
    title: "Астероид Бенну образовался в древнем океаническом мире",
    favourites: true,
    popular: true,
    author: 4,
  },
  {
    id: 8,
    image: "https://placehold.co/100x100",
    text: "Английский квартал — уникальная застройка. Он прописался в столичном «спальнике» и внес в окружающий его панельный квартал особую изюминку. Мы полюбовались мапидовскими панельками и даже заглянули на закрытый двор, спрятанный от глаз прохожих. Забегая вперед, отметим: этот комплекс совместил в себе два разных мира, объединенных сквозным подъездом.",
    date: "2021-12-12",
    lesson_num: 1,
    title:
      "Отвоевали дома у ЖЭСа, поставили забор и дразнят соседей из близлежащих панелек. Как поживает Английский квартал в белорусском «‎спальнике»?",
    favourites: true,
    popular: true,
    author: 5,
  },
  {
    id: 9,
    image: "https://placehold.co/100x100",
    text: "На форуме вновь споры о шумных соседях. На этот раз вопросы вызвало сверление стен в выходной день — кто-то решил повесить телевизор. «Вешать телевизор в выходные дни с 7 до 23 часов можно и не противоречит закону. Неудобно для соседей, накладно, но законно», — считают на форуме. Почему? Потому что это «не перепланировка, не переустройство и не реконструкция». А вы как считаете?",
    date: "2021-12-12",
    lesson_num: 1,
    title: "Можно ли по выходным сверлить стены? Некоторые считают, что можно",
    favourites: false,
    popular: false,
    author: 3,
  },
  {
    id: 10,
    image: "https://placehold.co/100x100",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "10 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: false,
    popular: false,
    author: 5,
  },
  {
    id: 11,
    image: "https://placehold.co/100x100",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "11 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: false,
    popular: false,
    author: 3,
  },
];
